spring:
  application:
    name: delivery

server:
  port: 8080

---
spring.config.activate.on-profile: local, test

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54321/delivery
    username: delivery
    password: delivery
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  main:
    allow-bean-definition-overriding: true


## JWT 설정
jwt:
  access:
    secret: CnzOb1c6g3kkY8QW+TwFl1DgNBFWtSEZamaHS+0BA/U=
    ttl: 15m
  refresh:
    secret: p/E81ODr93t/8QiN7FTQkeXqexA99gshuRSNd+or11g=
    ttl: 30d